Feature/offices&bankomats
RedMadRobot/omega-bank-ios pull request #11
Opened 2021-06-28 19:03 UTC by kos-tya

Верстка и кнопки увеличения/уменьшения карты

2021-06-29 09:14 UTC, vani2 approved these changes

2021-06-29 09:14 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    }
Пустые методы можно удалить

2021-07-03 08:19 UTC, vani2 requested changes

2021-07-03 08:19 UTC, vani2 commented on Source/OmegaBankFrameworks/OmegaBankAPI/Source/Model/Offices.swift
> +public struct Location: Decodable {
Используй [стандартный тип](https://developer.apple.com/documentation/corelocation/cllocation#)

2021-07-03 08:19 UTC, vani2 commented on Source/OmegaBankFrameworks/OmegaBankAPI/Source/Model/Offices.swift
> +//  Offices.swift
Назови файл Office, множественное число не используется, если это не какой-то исключительный случай.

2021-07-06 06:50 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private var progress: Progress?
Добавляем пустую строчку после MARK

2021-07-06 06:50 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private enum Constants {
MARK: - Constants

2021-07-06 06:52 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    static func make(delegate: ProfileViewControllerDelegate?) -> UIViewController {
Фабричный метод нужно вынести в фабрику, чтобы не идти против своей собственной [документации](https://github.com/RedMadRobot/omega-bank-ios/blob/master/Documentation/routing.md)

2021-07-06 06:52 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    override func viewDidLoad() {
Пустая строчка

2021-07-06 06:58 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        showMapCenter()
Кажется нужно подумать над бизнес логикой:

1. Сначала мы ставим на центр Москвы
2. Потом мы идем на позицию пользователя
3. Кажется нужно идти в центр Москвы только если доступ на навигацию к геопозиции пользователя запрещен

2021-07-06 07:02 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        let annotations: [MKAnnotation] = offices.compactMap { office in
Почему тут используешь `compactMap`?

2021-07-06 07:09 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            let annotation = MapAnnotation(
`MapAnnotation` строится только из офиса, соответственно можно именно его передать в конструктор, что позволит сократить размер контроллера и упростит чтение
Как второй вариант `MapAnnotation` можно сделать как computed property для офиса, причем через экстеншен:

```swift
extension Office {
    
    var annotation: MapAnnotation {
        MapAnnotation(
            latitude: location.latitude,
            longitude: location.longitude,
            title: name,
            subtitle: address)
    }
    
}
```

Причем этот extension должен быть в файле `MapAnnotation`, дабы не влиять на бизнес логику API клиента

И тогда метод будет выглядеть:

```swift
private func addAnnotations(_ offices: [Office]) {
        let annotations = offices.map { $0.annotation }
        mapView.addAnnotations(annotations)
    }
```

2021-07-06 07:14 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            locationManager.startUpdatingLocation()
Выглядит так что мы постоянно запрашиваем геопозицию пользователя, но показываем ее только раз

2021-07-06 07:16 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                  message: "Turn on on settings",
Опечатка

2021-07-06 07:19 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                        if UIApplication.shared.canOpenURL(settingsUrl) {
- Сначала `Guard`, потом `if`. Можно вообще сделать все в одном операторе.

2021-07-06 07:20 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        showAlert(title: "Geo settings are disabled",
Первый параметр уже должен быть перенесен

2021-07-06 07:20 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                  preferredAction: nil)
Конструктор наш, `preferredAction`, можно по дефолту выставить в `nil`

2021-07-06 07:21 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private func showMapCenter() {
Скорее `showMoscow`

2021-07-06 07:22 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                    latitude: Constants.coordinatesMoscow.latitude,
Проще вынести `CLLocationCoordinate2D` в константы целиком

2021-07-06 07:23 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        progress = officesService.load { [weak self] result in
Офисов я бы рекомендовал бы добавить, 1 мало

2021-07-06 07:25 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        var annotationView = mapView.dequeueReusableAnnotationView(
Кажется можно поступить по аналогии с Collection View. Смотри `UICollectionView+Nib.swift`

2021-07-08 15:57 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        let annotations: [MKAnnotation] = offices.compactMap { office in
забыл про обычный map

2021-07-08 16:37 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            locationManager.startUpdatingLocation()
показываем каждый раз когда меняется условия использования геолокации

2021-07-08 16:38 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                  message: "Turn on on settings",
подправил

2021-07-08 16:41 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                        if UIApplication.shared.canOpenURL(settingsUrl) {
исправил

2021-07-08 16:41 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        showAlert(title: "Geo settings are disabled",
перенес

2021-07-08 16:42 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                  preferredAction: nil)
выставил

2021-07-08 16:43 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private func showMapCenter() {
исправил

2021-07-08 16:46 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                    latitude: Constants.coordinatesMoscow.latitude,
Вынес

2021-07-08 16:51 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            let annotation = MapAnnotation(
исправил

2021-07-08 16:51 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        showMapCenter()
убрал

2021-07-08 16:52 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    override func viewDidLoad() {
убрал

2021-07-08 16:52 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    static func make(delegate: ProfileViewControllerDelegate?) -> UIViewController {
создал фабрику

2021-07-08 16:52 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private enum Constants {
добавил

2021-07-08 16:52 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    private var progress: Progress?
добавил

2021-07-08 17:15 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        var annotationView = mapView.dequeueReusableAnnotationView(
Переделал этот метод, теперь `mapView.dequeueReusableAnnotationView` – не используется

2021-07-08 18:30 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        progress = officesService.load { [weak self] result in
Добавил офисы, пока на пр

2021-07-09 08:19 UTC, vani2 requested changes

2021-07-09 08:19 UTC, vani2 commented on Source/OmegaBank/Sources/Application/AppViewController.swift
> +        factory: TabBarScreenFactory = ServiceLayer.shared.tabBarFactory) {
Считаю, что надо это исправить:
1. Фабрика VC – это UI, `ServiceLayer ` – это про UI. 
2. Эту фабрику в принципе нет смысла инкапсулировать в синглтон, нет состояние, которое надо хранить.

Делаешь так: 

```swift
init(
    loginService: LoginService = ServiceLayer.shared.loginService,
    factory: TabBarScreenFactory = TabBarScreenFactory()) {
```

2021-07-09 08:19 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MapAnnotation.swift
> +    var subtitle: String?
Можем `let` сделать

2021-07-09 08:19 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Map/Helper/MapAppsHelper.swift
> +final class MapAppsHelper {
Название неудачное, попытайся назвать исходя из того, что он делает.

2021-07-09 09:31 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/PageViewControllerFabric.swift
> +//  PageViewControllerFabric.swift
Переименовал

2021-07-09 09:32 UTC, kos-tya commented on Source/OmegaBank/Sources/Application/AppViewController.swift
> +        factory: TabBarScreenFactory = ServiceLayer.shared.tabBarFactory) {
Сделал

2021-07-09 09:32 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MapAnnotation.swift
> +    var subtitle: String?
Исправил

2021-07-09 09:32 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/MapAppsHelper.swift
> +final class MapAppsHelper {
Переименовал на AppsSchemasHelper

2021-07-09 10:02 UTC, vani2 approved these changes

2021-07-09 10:02 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Map/Helper/AppsSchemasHelper.swift
> +final class AppsSchemasHelper {
Уже лучше. Но Helper/Manager – слова-паразиты. Давай назовем `AppSchemeRouter`.

2021-07-11 17:46 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/AppsSchemasHelper.swift
> +final class AppsSchemasHelper {
Исправил

2021-07-12 09:15 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            locationManager.startUpdatingLocation()
Созвонимся, обсудим

2021-07-12 09:29 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +        alert.addAction(UIAlertAction(title: "Apple Maps", style: .default, handler: { _ in
В таких случаях удобнее использовать [trailing closure syntax](https://www.hackingwithswift.com/example-code/language/what-is-trailing-closure-syntax), так как особой информации это замыкание не несет

2021-07-12 09:33 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +        mapOptions.forEach { option in
Можно несколько упростить:

```swift
mapOptions
            .map { option in
                UIAlertAction(title: option.key, style: .default) { _ in
                    UIApplication.shared.open(option.value)
                }
            }
            .forEach { alert.addAction($0) }
```

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/Helper/Schemes/GoogleMapsScheme.swift
> +        let request = URLRequest(url: URL(string: stringScheme!)!)
- force unwrap избегаем
- ты возвращаешь url опциональный, предлагаю в таких случаях возвращать nil

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/Helper/Schemes/YandexMapsScheme.swift
> +    let scheme: URL? = URL(string: "yandexmaps://")
1. Схема это строка а не `URL`. А так все верно создаешь ура с помощью `URLComponents`
2. Вот пример: https://www.swiftbysundell.com/articles/constructing-urls-in-swift/

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                UIAlertAction(title: "Settings", style: .default, handler: { _ in
`handler` опускаем

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                    guard let settingsUrl = URL(string: UIApplication.openSettingsURLString),
Неправильный кодстайл для `guard`

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                break
Зеро-скрина не планируется?

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    // MARK: - IB Action
```suggestion
    // MARK: - IBAction
```

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            return }
Скобочка не там

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        guard !annotation.isKind(of: MKUserLocation.self) else {
Зачем этот `guard`?

2021-07-12 10:54 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            let view = dequeueReusableView(mapView: mapView, MarkerAnnotationView.self, for: annotation)
Можно вынести из `if`

```swift
let view = dequeueReusableView(mapView: mapView, MarkerAnnotationView.self, for: annotation)
```

2021-07-12 14:54 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/AppSchemeRouter.swift
> +            GoogleMapsScheme(annotation: annotation),
Сами карты используются apple, для прокладки маршрута к самой точке происходит проверка на наличие на устройстве установленных карт по типу apple maps, yondex maps, google maps

2021-07-12 16:44 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +        guard !annotation.isKind(of: MKUserLocation.self) else {
этот guard не дает поставить на нашу собственную геолокацию марку банкомата

2021-07-12 17:34 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +        alert.addAction(UIAlertAction(title: "Apple Maps", style: .default, handler: { _ in
Исправил

2021-07-12 17:34 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +        mapOptions.forEach { option in
Упростил

2021-07-12 17:34 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MarkerAnnotationView.swift
> +        label.font = UIFont.body2
Опустил

2021-07-12 17:35 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MarkerAnnotationView.swift
> +        let button = UIButton(frame: CGRect(origin: CGPoint.zero, size: CGSize(width: 32, height: 32)))
Опустил
Вынес в константы

2021-07-12 17:35 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MarkerAnnotationView.swift
> +
Убрал

2021-07-12 17:36 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/AppSchemeRouter.swift
> +            if let schemeUrl = scheme.scheme, UIApplication.shared.canOpenURL(schemeUrl), let url = scheme.url {
исправил

2021-07-12 17:36 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                break
добавил

2021-07-12 17:36 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +    // MARK: - IB Action
Исправил

2021-07-12 17:38 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/Schemes/GoogleMapsScheme.swift
> +        let request = URLRequest(url: URL(string: stringScheme!)!)
переделал

2021-07-12 17:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Helper/Schemes/YandexMapsScheme.swift
> +    let scheme: URL? = URL(string: "yandexmaps://")
переделал

2021-07-12 17:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                UIAlertAction(title: "Settings", style: .default, handler: { _ in
опустил

2021-07-12 17:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +                    guard let settingsUrl = URL(string: UIApplication.openSettingsURLString),
исправил

2021-07-12 17:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            return }
поправил

2021-07-12 17:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            let view = dequeueReusableView(mapView: mapView, MarkerAnnotationView.self, for: annotation)
вынес

2021-07-12 17:40 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/MapViewController.swift
> +            locationManager.startUpdatingLocation()
Изменил на `requestLocation()`

2021-07-13 06:41 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +                    UIApplication.shared.open(option.value, options: [:], completionHandler: nil)
```swift
UIApplication.shared.open(option.value)
```

2021-07-13 06:48 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MarkerAnnotationView.swift
> +        let button = UIButton(frame: CGRect(origin: CGPoint.zero, size: CGSize(width: 32, height: 32)))
Имел ввиду вот так:

```swift
private let mapsButton: UIButton = {
        let button = UIButton(frame: Constants.mapButtonFrame)
        button.setBackgroundImage(Asset.maps.image, for: .normal)
        return button
    }()
   ```

2021-07-13 07:35 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Map/Annotations/MarkerAnnotationView.swift
> +        let button = UIButton(frame: CGRect(origin: CGPoint.zero, size: CGSize(width: 32, height: 32)))
Исправил

2021-07-13 07:35 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/View/Helper/AlertPresentable.swift
> +                    UIApplication.shared.open(option.value, options: [:], completionHandler: nil)
Исправил

2021-07-13 07:44 UTC, merged