Feature/pincode
RedMadRobot/omega-bank-ios pull request #7
Opened 2021-06-10 16:05 UTC by yourdearrobot

Реализовал экраны, с валидацией и логикой UI:
Создания пин-кода
Входа по пин-коду 

Переключить экраны и посмотреть их можно в AppDelegate

2021-06-11 07:09 UTC, vani2 commented
<img width="400" alt="Screenshot 2021-06-11 at 10 08 34" src="https://user-images.githubusercontent.com/4734983/121645597-0c4d4980-ca9d-11eb-82f5-c3d8eadd1e91.png">
Почему-то pin code button отдельно лежит от pin code views, перенеси из common, что относится к пин коду.

2021-06-11 07:36 UTC, n-zhukov commented
Слева и справа белые поля кажутся лишними

![Screenshot 2021-06-11 at 11 34 05](https://user-images.githubusercontent.com/64949800/121649012-28ef7e80-caa9-11eb-909b-7da6744e9d41.png)

2021-06-11 07:59 UTC, n-zhukov commented
Понимаю что дизайн уже согласован, но:

1. Хочется добавить паддинг у всей клавиатуры как в бехансе
2. Предлагаю немного уменьшить область выделения. Фиолетовые кружки, когда тапаем

2021-06-11 08:07 UTC, n-zhukov commented on Source/OmegaBank/Resources/Assets.xcassets/Images/Background/background.imageset/Contents.json
> +      "filename" : "background.pdf",
Изображения с градиентами обычно вставляем как PNG-ку

2021-06-11 08:10 UTC, vani2 requested changes

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +    @IBOutlet var rightButton: UIButton!
```suggestion
    @IBOutlet private var leftButton: UIButton!
    @IBOutlet private var rightButton: UIButton!
```

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Common/Appearence/Color.swift
>      // MARK: - Backgound Colors
```suggestion
    // MARK: - Background Colors
```

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Common/Appearence/Image.swift
> +    static var background: UIImage { UIImage(named: #function)! }
Давай подключим `SwiftGen`, чтобы это не делать руками.

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Common/View/Button/PinCodeButton.swift
> +class PinCodeButton: UIButton {
А мы используем эту кнопку кроме как в связке с `PinCodeDigitButton`?

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Common/View/Button/PinCodeDigitButton.swift
> +            backgroundColor = isHighlighted ? UIColor.bar2 : UIColor.white
```suggestion
            backgroundColor = isHighlighted ? .bar2 : .white
```

2021-06-11 08:10 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +    func showError() { indicatorViews.forEach { $0.backgroundColor = UIColor.red } }
```suggestion
    func showError() { indicatorViews.forEach { $0.backgroundColor = .red } }
```

2021-06-11 12:56 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/View/Button/PinCodeButton.swift
> +class PinCodeButton: UIButton {
Добавил описание для кнопки + изменил название, кажется, что зря описание давал

2021-06-16 10:38 UTC, vani2 requested changes

2021-06-16 10:38 UTC, vani2 commented on Source/OmegaBank/Sources/Application/AppViewController.swift
> +        }
А тут можно просто `tabBar.isHidden = false` для всех случаев?

2021-06-16 10:38 UTC, vani2 commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +            guard self != nil else { return }
А зачем? Это не нужно.

2021-06-16 10:38 UTC, vani2 commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +                if let error = error {
Тут лучше написать `else if let`. Вряд ли там будет success = true и error одновременно, но читается проще.

2021-06-16 10:38 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeBaseViewController.swift
> +            guard self != nil else { return }
Эти проверки не нужны

2021-06-16 10:38 UTC, vani2 commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +        ) throws -> Void)
`throws` для `completion` не нужен

2021-06-18 09:16 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +    private func clear(completion: (() -> Void)?) {
не увидел коммент ранее,
сделал отдельный файл и переименовал в проекте, до куда смог достать

2021-06-18 09:26 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +            isUserInteractionEnabled = isEnabled
не увидел коммент ранее, исправил

2021-06-18 10:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/Appearence/Image.swift
> +    static var background: UIImage { UIImage(named: #function)! }
Цвета тоже переведем?

2021-06-18 10:05 UTC, kos-tya commented on Source/OmegaBank/Sources/Application/AppViewController.swift
> +        }
Добавил для всех случаев, но есть исключение, когда в одну сессию авторизуемся и деавторизуемся

2021-06-18 11:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +            guard self != nil else { return }
Убрал

2021-06-18 11:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +                if let error = error {
Исправил

2021-06-18 11:39 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeBaseViewController.swift
> +            guard self != nil else { return }
Убрал

2021-06-18 11:40 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +        ) throws -> Void)
Если его убрать, то в LoginService мы не сможем поймать ошибку авторизации

2021-06-18 11:40 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +        ) throws -> Void)
Виноват, LoginService с методами авторизации еще не запушил

2021-06-18 11:41 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +    override func loadView() {
Добавил

2021-06-18 11:46 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +        view.backgroundColor = .white
Заменил на .defaultBackground

2021-06-18 11:47 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +    // MARK: - Public methods
Исправил

2021-06-18 11:55 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +    func updateRightButton() {
Переписал

2021-06-18 11:56 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +    func clearInput(with animation: ClearAnimation) {
Исправил

2021-06-18 11:58 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeController.swift
> +            guard self != nil else { return }
Исправил, вынес время константу

2021-06-18 12:00 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeCreateViewController.swift
> +    // MARK: - Init
На будущее делал, сейчас он не пустой

2021-06-18 12:01 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeCreateViewController.swift
> +    // MARK: - VC
Исправил

2021-06-18 12:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeCreateViewController.swift
> +            isEnabledKeyboard = true
Исправил

2021-06-18 12:04 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeCreateViewController.swift
> +    private func save() {
Теперь не пустой

2021-06-18 12:10 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeCreateViewController.swift
> +    @objc override func pinCodeKeyboardView(_ keyboard: PinCodeKeyboardView, didSelect number: String) {
Добавил

2021-06-18 12:10 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeEntryViewController.swift
> +    // Кол-бэк на вход
Заменил коллбэки на делегаты, убрал документацию

2021-06-18 12:28 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeEntryViewController.swift
> +    private var wrongInputAttempts = 3
Не константа, число используется и в дальнейшем уменьшается при попытках не корректного ввода пин-кода

2021-06-18 12:29 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +                view.backgroundColor = index < value ? UIColor.bar2 : UIColor.cellBorder
Убрал

2021-06-18 12:30 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +    func showError() { indicatorViews.forEach { $0.backgroundColor = UIColor.red } }
Убрал

2021-06-18 12:32 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +        switch animation {
Для выбора нужной анимации, была не верная анимация, подправил

2021-06-18 13:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +                withDuration: 0.2,
Перенес в константы

2021-06-18 13:04 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +    @IBOutlet var leftButton: UIButton!
Исправил

2021-06-18 13:18 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +            rightButton.isEnabled = true
Изменил условие

2021-06-18 13:47 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +            rightButton.tintColor = UIColor.ph3
выставил в кнопке

2021-06-18 13:54 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
> +    func setLeftButton(name: String?) {
заменил

2021-06-18 13:55 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +// MARK: - Types
Добавил

2021-06-18 13:57 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +            if isHiddenExitButton {
исправил

2021-06-18 14:47 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        image.frame.size = CGSize(width: 72, height: 72)
Убрал, размеры задаются с помощью картинки

2021-06-18 14:47 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        image.layer.cornerRadius = 36
Перенес в константы

2021-06-18 14:47 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        image.image = UIImage.defaultUser
Опустил

2021-06-18 14:51 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        label.font = UIFont.systemFont(ofSize: 16, weight: .medium)
перенес в Font

2021-06-18 14:51 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        label.font = UIFont.systemFont(ofSize: 24, weight: UIFont.Weight.medium)
Опустил

2021-06-18 14:51 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        image.frame.size = CGSize(width: UIScreen.main.bounds.width, height: (UIScreen.main.bounds.width / 3))
Убрал

2021-06-18 14:59 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +            keyboardView.setRightButton(image: UIImage.backspace)
Исправил

2021-06-18 15:02 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        keyboardView.layer.shadowOpacity = 0.2
Вынес в константы

2021-06-18 16:06 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
Исправил

2021-06-18 16:06 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +            stackView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -24)
Перенес

2021-06-18 17:00 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        stackView.setCustomSpacing(15.0, after: imageView)
не совсем понял

2021-06-18 17:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Common/View/Button/PinCodeButton.swift
> +        CGSize(width: 72, height: 72)
Перенес в константы

2021-06-18 17:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Application/AppViewController.swift
> +// MARK: - PinCodeCreateViewControllerDelegate
Добавил

2021-06-18 17:04 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +        let context = LAContext()
Добавил

2021-06-18 17:05 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeBaseViewController.swift
> +    // MARK: - Public methods
Исправил

2021-06-18 17:34 UTC, kos-tya commented
Чтобы проверить биометрию и ввод пин-кода, нужно на реальный девайс поставить МП, без него биометрия и проверка – работать не будут

2021-06-21 06:13 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        stackView.setCustomSpacing(15.0, after: imageView)
Предлагаю созвониться

2021-06-21 06:17 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeBaseViewController.swift
> +        UIView.appearance().isExclusiveTouch = true
Что хотел этим сделать?

2021-06-21 06:19 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
>      func setRightButton(image: UIImage?) {
Метод можно упростить:

```swift
func setRightButton(image: UIImage?) {
        rightButton.isEnabled = image != nil
        rightButton.setImage(image, for: .normal)
    }
```

2021-06-21 06:22 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +            backgroundImage.widthAnchor.constraint(
Для добавления UIView и установки ей констрейнтов используем хелпер метод:

```swift
func addSubview(_ subview: UIView, activate constraints: @autoclosure () -> [NSLayoutConstraint])
```

2021-06-21 07:01 UTC, vani2 commented on Source/OmegaBank/Sources/Business Logic/Service/BiometricService.swift
> +        ) throws -> Void)
Да, то есть он вообще не нужен

2021-06-21 07:03 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeBaseViewController.swift
> +        UIView.appearance().isExclusiveTouch = true
перенести на keyboardview

2021-06-21 07:18 UTC, vani2 approved these changes

2021-06-21 07:18 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/Common/Alert/UIViewController+AlertExtension.swift
> +    func showAuthenticationAlert(completion: @escaping (Bool) -> Void) {
Так лучше не делать. Это чревато, что у `UIViewController` будет куча методов, которые можно вызвать из любого места.
Обычно мы делаем `extension` на `UIAlertController` с фабричными функциями `make` для создания конкретного `Alert`. Либо можно сделать `protocol extension`.

Пока в проекте нет примеров через `make`, давай сделаем через `protocol extension`.

2021-06-21 07:18 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/Common/Alert/UIViewController+AlertExtension.swift
> +            message: "Так вы сможете быстрее авторизовываться в нём",
Кажется, что у нас заголовки и моки на англ языке, лучше перевести.

2021-06-21 07:18 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeIndicatorView.swift
> +    @IBOutlet private var indicatorViews: [UIView]!
Кстати, насчет порядка не уверен, что он будет соблюдаться. @kos-tya можешь про это найти в документации?

2021-06-21 07:18 UTC, vani2 commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeEntryViewController.swift
> +            return }
```suggestion
            return 
        }
```

2021-06-21 11:35 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        stackView.setCustomSpacing(15.0, after: imageView)
Сделать кастомный спейсинг = 15

2021-06-21 11:57 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +        stackView.setCustomSpacing(15.0, after: imageView)
Исправил

2021-06-21 12:04 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeKeyboardView.swift
>      func setRightButton(image: UIImage?) {
Исправил

2021-06-21 12:04 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View/PinCodeView.swift
> +            backgroundImage.widthAnchor.constraint(
Исправил

2021-06-21 12:05 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/Common/Alert/UIViewController+AlertExtension.swift
> +    func showAuthenticationAlert(completion: @escaping (Bool) -> Void) {
Исправил

2021-06-21 12:05 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/Common/Alert/UIViewController+AlertExtension.swift
> +            message: "Так вы сможете быстрее авторизовываться в нём",
Перевел весь флоу создания пин-кода

2021-06-22 16:49 UTC, n-zhukov commented on Source/OmegaBank/Sources/Business Logic/Service/LoginService.swift
> +                    if let pinCode = try self.accessTokenStorage.getPinCode(withBiometry: context) {
guard в таких случаях предпочтительнее использовать чем if. Это уменьшает вложенность

2021-06-22 16:50 UTC, n-zhukov commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeEntryViewController.swift
> +        authoriseBiometry()
после вызова метода родительского класса "super" обычно ставим пустую строчку

2021-06-22 16:52 UTC, n-zhukov reviewed
Отлично

2021-06-23 07:25 UTC, vani2 approved these changes

2021-06-23 08:07 UTC, kos-tya commented on Source/OmegaBank/Sources/Business Logic/Service/LoginService.swift
> +                    if let pinCode = try self.accessTokenStorage.getPinCode(withBiometry: context) {
поправил

2021-06-23 08:07 UTC, kos-tya commented on Source/OmegaBank/Sources/Presentation/Auth/PinCode/View Contorller/PinCodeEntryViewController.swift
> +        authoriseBiometry()
поправил

2021-06-23 08:16 UTC, merged